[package]
name = "descriptor-mapping"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bytes = "1.6.0"
once_cell = "1.19.0"
prost-reflect = "0.13.1"
prost-reflect-build = "0.13.0"
serde_json = "1.0.117"
tracing = "0.1.40"
